# Generated by Django 4.2.7 on 2026-02-06 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0008_userprofile_alter_attemptedmock_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("pdf_purchase", "PDF Purchase"),
                            ("pdf_view", "PDF View"),
                            ("mock_attempt", "Mock Test Attempt"),
                            ("mock_complete", "Mock Test Complete"),
                            ("quiz_attempt", "Quiz Attempt"),
                            ("quiz_complete", "Quiz Complete"),
                            ("interview_attempt", "Interview Attempt"),
                            ("interview_complete", "Interview Complete"),
                            ("video_watch", "Video Watch"),
                            ("profile_update", "Profile Update"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User Activities",
                "ordering": ["-created_at"],
            },
        ),
    ]
